# My Jupyter Notebook on IBM Data Science Experience

**Courtney T Green**  
Data Scientist for an Education Initiative

*I am interested in data science because it is an effective way to use my curiosity and love for Statistics to help children.*

### Calculate the the difference between my husband's age and my age

In [1]:
33-29

Waiting for a Spark session to start...
Spark Initialization Done! ApplicationId = app-20200409220037-0000
KERNEL_ID = dfcf5546-7a13-40e2-be9f-2f03ab60e9ab

4

1. Courtney
2. Danny
3. Brutus Bobby

 * peanut butter
 * chocolate
 * dog treats  
 * ~~popcorn~~  
 
 ___  
 > Can anyone tell me why my table wouldn't show up properly at first? I used the same method of creating a table that I used in the skills network lab, but it wasn't  appearing correctly. I've decided to do this **blockquote** to bring attention to it. Only when I saved the notebook did it work properly.  
 
 
   Name | Age | Snack   
  :----: | :----: | :----:   
  Danny | 33 | peanut butter   
  Courtney | 29 | chocolate   
  Brutus Bobby | 6 | dog treats